export const portfolioTemplates = [
    {
        id: 'blog-minimal',
        name: 'Blog Minimal',
        category: 'Blog',
        description: 'Clean and minimal blog portfolio template',
        icon: '📝',
        color: '#4f46e5',
        preview: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=400&h=300&fit=crop',
        sections: ['hero', 'about', 'blog', 'contact'],
    },
    {
        id: 'corporate-pro',
        name: 'Corporate Pro',
        category: 'Corporate',
        description: 'Professional corporate portfolio with services',
        icon: '🏢',
        color: '#1e3a8a',
        preview: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop',
        sections: ['hero', 'about', 'services', 'team', 'contact'],
    },
    {
        id: 'agency-creative',
        name: 'Agency Creative',
        category: 'Agency',
        description: 'Creative agency portfolio with projects showcase',
        icon: '🎨',
        color: '#dc2626',
        preview: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop',
        sections: ['hero', 'portfolio', 'services', 'testimonials', 'contact'],
    },
    {
        id: 'hotel-luxury',
        name: 'Hotel Luxury',
        category: 'Hotel',
        description: 'Luxury hotel portfolio with rooms showcase',
        icon: '🏨',
        color: '#7c3aed',
        preview: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=300&fit=crop',
        sections: ['hero', 'rooms', 'amenities', 'gallery', 'booking', 'contact'],
    },
    {
        id: 'business-modern',
        name: 'Business Modern',
        category: 'Business',
        description: 'Modern business portfolio with features',
        icon: '💼',
        color: '#0891b2',
        preview: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop',
        sections: ['hero', 'features', 'pricing', 'testimonials', 'contact'],
    },
    {
        id: 'restaurant-elegant',
        name: 'Restaurant Elegant',
        category: 'Restaurant',
        description: 'Elegant restaurant portfolio with menu',
        icon: '🍽️',
        color: '#c2410c',
        preview: 'https://images.unsplash.com/photo-1504674900967-a8f32de4a645?w=400&h=300&fit=crop',
        sections: ['hero', 'menu', 'about', 'gallery', 'reservations', 'contact'],
    },
    {
        id: 'pharmacy-health',
        name: 'Pharmacy Health',
        category: 'Pharmacy',
        description: 'Health-focused pharmacy portfolio',
        icon: '💊',
        color: '#0f766e',
        preview: 'https://images.unsplash.com/photo-1576091160550-112173f7f869?w=400&h=300&fit=crop',
        sections: ['hero', 'services', 'products', 'about', 'contact'],
    },
    {
        id: 'gym-fitness',
        name: 'Gym Fitness',
        category: 'Gym',
        description: 'Dynamic gym and fitness portfolio',
        icon: '💪',
        color: '#dc2626',
        preview: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=300&fit=crop',
        sections: ['hero', 'classes', 'trainers', 'pricing', 'testimonials', 'contact'],
    },
]
